#/*******************************************************************************
# * Name        : sort.c
# * Author      : Joshua Schmidt
# * Date        : 2/10/20
# * Pledge      : I pledge my honor that I have abided by the Stevens Honor System.
# * Description : makefile for quicksort
# ******************************************************************************/

