#/*******************************************************************************
# * Name        : main.c
# * Author      : Joshua Schmidt and Matt Evanago
# * Date        : 3/13/20
# * Pledge      : I pledge my honor that I have abided by the Stevens Honor System.
# * Description : create n forks
# ******************************************************************************/

CC     = gcc
C_FILE = nforks.c
TARGET = nforks
CFLAGS = -Wall -Werror -pedantic-errors

all:
	$(CC) $(CFLAGS) $(C_FILE) -o $(TARGET)
clean:
	rm -f $(TARGET) $(TARGET).exe
