#/*******************************************************************************
# * Name        : makefile
# * Author      : Joshua Schmidt and Matt Evanago
# * Date        : 3/27/20
# * Pledge      : I pledge my honor that I have abided by the Stevens Honor System.
# * Description : print cpu model
# ******************************************************************************/

CC     = gcc
C_FILE = cpumodel.c
TARGET = cpumodel
CFLAGS = -Wall -Werror -pedantic-errors

all:
	$(CC) $(CFLAGS) $(C_FILE) -o $(TARGET)
clean:
	rm -f $(TARGET) $(TARGET).exe
